services:
  proceed_research_management_system:
    image: proceed/ms-server:edge
    container_name: proceed_research_management_system
    env_file: .env.research
    restart: always
    ports:
      - '33081:33081'
    depends_on:
      - proceed_research_postgres_database
    volumes:
      - ./proceed-ms-filesystem-data:/app/volume
    networks:
      - proceed-network

  proceed_research_postgres_database:
    image: postgres:latest
    container_name: proceed_research_postgres_database
    env_file: .env.research
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - proceed_research_postgres_db:/var/lib/postgresql
    networks:
      - proceed-network

volumes:
  proceed_research_postgres_db:

networks:
  proceed-network:
    name: proceed-production-network
    external: true
